---
- name: RBenv dependencys for ruby
  register: rubydependency
  apt:
    pkg:
    - autoconf
    - bison
    - build-essential
    - libssl-dev
    - libyaml-dev
    - libreadline6-dev
    - zlib1g-dev
    - libncurses5-dev
    - libffi-dev
    - libgdbm6
    - libgdbm-dev
    - libdb-dev
    - patch
    - rustc
    - uuid-dev

- name: Download rbenv install for ruby
  register: rbenvinstaller
  become: false
  shell:
    cmd: curl -fsSL https://github.com/rbenv/rbenv-installer/raw/HEAD/bin/rbenv-installer | bash
    warn: false

- name: Add rbenv and gem path to .bashrc
  register: bashrcmodify
  become: false
  ansible.builtin.blockinfile:
    path: ~/.bashrc
    backup: yes
    block: |
      export PATH="$HOME/.rbenv/bin:$PATH"
      eval "$(rbenv init -)"
      export GEM_HOME="$HOME/gems"
      export PATH="$HOME/gems/bin:$PATH"

- name: Install latest ruby
  register: installruby
  become: false
  async: 600
  shell: |
      export PATH="$HOME/.rbenv/bin:$PATH"
      eval "$(rbenv init -)"
      rbenv install "{{ ruby_version }}"
      rbenv global "{{ ruby_version }}"

  args:
    executable: /bin/bash

- name: Check installation results of ruby "{{ ruby_version }}"
  debug:
    var: installruby.stdout
