- name: Works on my machine
  hosts: 127.0.0.1
  connection: local
  vars_files:
    - ./variables.yaml
  become: true
  gather_facts: true

  tasks:
  - name: Set install_jekyll for legacy support
    set_fact:
      install_jekyll: "{{ true if install_nodejs|bool and install_ruby|bool else false }}"
    when: install_jekyll is undefined

  - name: Set install_clone_repo_single for legacy support
    set_fact:
      install_clone_repo_single: "{{ true if GitRepo is defined else false }}"
    when: install_clone_repo_single is undefined

  - name: Find available roles
    find:
      paths: roles
      recurse: no
      file_type: directory
    register: roles_find_result
    delegate_to: 127.0.0.1

  - name: Create list of available roles
    set_fact:
      roles_available: "{{ roles_available | default([]) + [ item.path | basename ] }}"
    with_items:
    - "{{ roles_find_result.files }}"

  - name: Decide with roles to run
    set_fact:
      roles_to_run: "{{ roles_to_run | default([]) + [ item ] if lookup('vars', 'install_' + (item | regex_replace('^[0-9]+_', '')), default=true)|bool else roles_to_run | default([])}}"
    with_items:
    - "{{ roles_available }}"

  - name: Smalltalk with the repos if older 1h
    register: systemupdate
    apt:
      update_cache=yes
      force_apt_get=yes
      cache_valid_time=3600

  - name: Run roles
    include_role:
      name: "{{ role }}"
    loop: "{{ roles_to_run }}"
    loop_control:
      loop_var: role
