---
- name: Install Docker apt requirements
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - ca-certificates
      - lsb-release
      - gnupg
    state: latest
    update_cache: true

- name: Add Docker signing key
  ansible.builtin.apt_key:
    url: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg"
    state: present

- name: Add repository docker into sources list
  ansible.builtin.apt_repository:
    repo: "deb [arch={{ docker_apt_arch }}] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"
    state: present
    filename: docker

- name: Install Docker
  ansible.builtin.apt:
    name:
      - docker
      - docker.io
      - docker-registry
      - docker-compose-plugin
    state: latest
    update_cache: true

- name: Adding user to secondary group docker
  ansible.builtin.user:
    name: "{{ ansible_facts['env']['SUDO_USER'] }}"
    groups: docker
    append: true
